# Generated by Django 5.2.5 on 2025-08-26 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'month', 'year')},
        ),
    ]
