# Generated by Django 5.2.5 on 2025-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_budget_created_at_budget_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='spent',
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
    ]
